name: CI Pipeline ESBD3

on:
  push:
    branches:['main']
  pull_request:
    branches:['main']

jobs:
  build-and-test:
    runs-on: ubunt_lastest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Configurar python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Rodar testes automatizados
        run: pytest test_pipeline.py
